# Use `Ctrl-a` as the prefix key instead of `Ctrl-b` like GNU Screen
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes with `|` and `-`
bind-key -r | split-window -h
bind-key -r - split-window -v

# Resize panes with arrow keys
bind-key -r Up resize-pane -U 5
bind-key -r Down resize-pane -D 5
bind-key -r Left resize-pane -L 5
bind-key -r Right resize-pane -R 5

# Status bar
set -g status on
set -g status-position bottom
set -g status-bg black
set -g status-fg magenta

# Enable mouse support (clickable panes, scroll)
set-option -g mouse on
